### ISSUE TITLE
The help message.

### ISSUE THREAD

**Issue by andreiarusoaie** [alk-language/java-semantics#2]
None of the options `-h`, `--h`, `-help` or `--help` works. Since these are pretty common when working with command line tools, it would be nice to have them in Alk as well. Here's what I tried:

```
andrei@pc:~/work/temp/java-semantics$ ./bin/alki.sh -help
java.io.FileNotFoundException: -help (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at main.Main.main(Main.java:76)
andrei@pc:~/work/temp/java-semantics$ ./bin/alki.sh --help
java.io.FileNotFoundException: --help (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at main.Main.main(Main.java:76)
andrei@pc:~/work/temp/java-semantics$ ./bin/alki.sh -h
java.io.FileNotFoundException: -h (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at main.Main.main(Main.java:76)
andrei@pc:~/work/temp/java-semantics$ ./bin/alki.sh --h
java.io.FileNotFoundException: --h (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at main.Main.main(Main.java:76)
```

**Comment by dlucanu** [comment]
The design of the option language for the command line is in progress. The current syntax for the command line is the simplest one that allow to use the interpreter. Any help is welcome.
